### ISSUE TITLE
[Bug] SCA sometimes errors on valid lexurgy change list

### ISSUE THREAD

**Issue by Annwan** [Sirraide/smyth#14]
When processing lexurgy sound changes, sometimes the SCA decides to not apply any rule (and selecting any rule in the apply until menu raises a "no such rule" error (see image)
![Screenshot_20240505_135248](https://github.com/Sirraide/smyth/assets/30665559/546abf54-43ee-4b2b-a326-7938fc6ab9d3)

The sound changes work just fine on the Lexurgy SC website

[Example of a change set that triggers the behaviour](https://github.com/Sirraide/smyth/files/15212817/sample-lexurgy.txt)

**Comment by Sirraide** [comment]
We were not actually sending the sound changes, somehow. Fixed.
